http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

  services: {}
